"""
Reinforcement learning module for AutoClean rule extractors.

This module implements a simple feedback mechanism that adjusts the
strictness of individual rule extractors based on user feedback.  When
users approve rules generated by a particular extractor, the model
interprets this as a signal that the extractor is too conservative and
should relax its heuristics slightly to capture more candidate rules
next time.  Conversely, when users reject rules, the model tightens
heuristics for that extractor to reduce noisy or low‑quality rules.

Strictness scores are persisted to a JSON file defined by
`settings.rl_config_path`.  Scores are floats typically in the range
``[-2.0, 2.0]``.  A higher score implies the extractor should be
stricter (fewer rules), whereas a lower score implies more lenient
heuristics (more rules).  Each extractor interprets the score by
linearly adjusting its internal thresholds around sensible defaults.

The update rule is simple: each approval decreases the strictness
score by a fixed learning rate, and each rejection increases it by the
same amount.  Scores are clamped to a reasonable range to prevent
unbounded growth.  If a rule's category cannot be mapped to a known
extractor, the feedback is ignored.
"""

from __future__ import annotations

import json
import os
from typing import Dict, Optional

# Import settings from parent package.  Using a relative import from
# ``..config`` instead of ``.config`` because ``config.py`` resides
# in the parent ``app`` package, not within the ``services`` package.
from ..config import settings  # type: ignore


# Default initial strictness values for each extractor.  A value of
# zero indicates that the extractor should use its default thresholds.
DEFAULT_SCORES: Dict[str, float] = {
    "regex": 0.0,
    "range": 0.0,
    "categorical": 0.0,
    "uniqueness": 0.0,
    "fd": 0.0,
    "anomaly": 0.0,
    "missing": 0.0,
    "semantic": 0.0,
    "multi": 0.0,
}


def _load_scores() -> Dict[str, float]:
    """Load strictness scores from the config file.

    If the file does not exist or cannot be parsed, return a copy of
    DEFAULT_SCORES.  Unknown extractor keys in the file are ignored.
    """
    path = settings.rl_config_path
    try:
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
                scores = {}
                for key, value in data.items():
                    if key in DEFAULT_SCORES:
                        try:
                            scores[key] = float(value)
                        except Exception:
                            scores[key] = DEFAULT_SCORES[key]
                # Ensure all keys exist
                for k in DEFAULT_SCORES:
                    scores.setdefault(k, DEFAULT_SCORES[k])
                return scores
    except Exception:
        # Fall back to defaults on any error
        pass
    return DEFAULT_SCORES.copy()


def _save_scores(scores: Dict[str, float]) -> None:
    """Persist strictness scores to the config file.

    Creates the directory if necessary and writes JSON atomically by
    writing to a temporary file first and then renaming.
    """
    path = settings.rl_config_path
    # Ensure parent directory exists
    try:
        parent = os.path.dirname(path)
        if parent and not os.path.exists(parent):
            os.makedirs(parent, exist_ok=True)
    except Exception:
        # Best effort; ignore errors
        pass
    tmp_path = f"{path}.tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump(scores, f, indent=2)
        os.replace(tmp_path, path)
    except Exception:
        # If we cannot write, silently ignore and do not persist
        pass


def get_strictness(extractor: str) -> float:
    """Get the current strictness score for a given extractor.

    Args:
        extractor: One of the keys defined in DEFAULT_SCORES.

    Returns:
        The strictness score (float).  A higher score means stricter
        heuristics; a lower score means more relaxed heuristics.
    """
    scores = _load_scores()
    return scores.get(extractor, 0.0)


def update_strictness(extractor: str, delta: float) -> None:
    """Update the strictness score for an extractor.

    The update adds ``delta`` to the current score and clamps the
    result to the range ``[-2.0, 2.0]``.  Positive ``delta``
    increases strictness (fewer rules); negative ``delta`` decreases
    strictness (more rules).

    Args:
        extractor: Extractor name.
        delta: Amount to adjust the strictness by.
    """
    if extractor not in DEFAULT_SCORES:
        return
    scores = _load_scores()
    current = scores.get(extractor, 0.0)
    new_value = max(-2.0, min(2.0, current + delta))
    scores[extractor] = new_value
    _save_scores(scores)


def feedback_on_rule(rule: "models.Rule", approval: Optional[bool]) -> None:
    """Handle user feedback on a rule.

    This function inspects the rule's curation category and source to
    determine which extractor generated it.  Approved rules are
    interpreted as a signal to relax the corresponding extractor's
    heuristics (negative delta), while rejected rules increase
    strictness (positive delta).  Pending (None) approvals have no
    effect.

    Args:
        rule: SQLAlchemy Rule ORM object.
        approval: True for approved, False for rejected, None for
            pending/undecided.
    """
    # Ignore pending approvals
    if approval is None:
        return
    try:
        from .db import models  # Local import to avoid circular dependency
    except Exception:
        return
    # Determine extractor from rule's curation category or source
    extractor = None
    # Use curation category if available
    if isinstance(rule.targets, dict):
        curation = rule.targets.get("curation") if rule.targets else None
        if isinstance(curation, dict):
            category = curation.get("category")
            if isinstance(category, str):
                category = category.lower()
                # Map curator categories to extractor keys
                mapping = {
                    "format": "regex",
                    "regex": "regex",
                    "pattern": "regex",
                    "range": "range",
                    "categorical": "categorical",
                    "identifier": "uniqueness",
                    "dependency": "fd",
                    "outlier": "anomaly",
                    "missing": "missing",
                    "standardization": None,
                    "semantic": "semantic",
                    "other": None,
                }
                extractor = mapping.get(category)
    # If not found from category, fall back to rule source
    if not extractor:
        src = str(rule.source.value).lower() if hasattr(rule.source, "value") else str(rule.source).lower()
        if src == "rag":
            extractor = "semantic"
        elif src == "extracted":
            # Without category, treat as generic multi extractor
            extractor = "multi"
        else:
            extractor = None
    if not extractor:
        return
    # Determine delta: approved -> negative, rejected -> positive
    delta = -0.1 if approval else 0.1
    update_strictness(extractor, delta)